### ISSUE TITLE
Pygame arena display

### ISSUE THREAD

**Issue by mxl0velace** [DaveTheTroll/RobotArena#3]
There should be a pygame display of an arena - using information from the server to draw robots on a pygame surface, constantly updating. This could lead on to accessing the arenas without having to go on the web page. It will start with basic graphics (basic shapes on a plain background) but will progress to being the main display, better than the webpage.

**Comment by DaveTheTroll** [comment]
This basic implementation is complete all future changes should be raised as issues.
